# Generated by Django 5.0.1 on 2024-01-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='category',
            field=models.CharField(default='default_category', max_length=50),
        ),
    ]
