# Generated by Django 5.0.1 on 2024-01-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartProjectApp', '0002_picture_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
